### PR TITLE
Add ability to iterate with TraverseDirectionReverse 

### PR DESCRIPTION
**Pull request by recoilme**

### CODE REVIEW

**Comment by plar** [comment]
1. Could you fix `./tree_test.go:1154: undefined: sort.Slice`? (remove old golang versions 1.8, 1.7, etc from the travis file)
2. It would be nice to extend Reverse functionality to `Iterator` as well to make it consistent with `ForEach`

**Comment by recoilme** [comment]
I will take a look at it, thx! 
Like your architecture and code quality, nice project

**Comment by recoilme** [comment]
>     2\. It would be nice to extend Reverse functionality to `Iterator` as well to make it consistent with `ForEach`

Don't know how to implement this correctly, without ugly code duplications like in foreach

**Comment by prologic** [comment]
Why did this not get finished and merged? 🤔

**Pull request closed without merging**
